---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
        tier: db
        component: mysql
        project: expense
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #targetport