
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  # these labels belongs to replicaset resource
  #namespace: expense
  labels:
    tier: web
    component: frontend
    project: expense
spec:
  # modify replicas according to your case
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      tier: web
      component: frontend
      project: expense
  # below is pod definition    
  template:
    metadata:
    # these labels belongs to pod
      labels:
        tier: web
        component: frontend
        project: expense
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.imageversion }}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
            name: frontend
            items:
            - key: nginx.conf
              path: nginx.conf      




