---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  #namespace: expense
spec:
  type: LoadBalancer
  selector:
        tier: web
        component: frontend
        project: expense
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 8080 #targetport