apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
        tier: app
        component: backend
        project: expense
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #targetport